### ISSUE TITLE
Вынеси пароль в конфиг

### ISSUE THREAD

**Issue by nking07049925** [Inevitabilis/RegionLease#1]
https://github.com/Inevitabilis/RegionLease/blob/3c448f3310a48348cb4aef930f3fd40bc7c5fc73/src/datasource.ts#L10C29-L10C49
```ts
  password: fs.readFileSync("D:\\dbpwd.txt", "utf8").trim(),
```

**Comment by Inevitabilis** [comment]
что такое конфиг и разве я не должен наоборот скрывать пароль?
